apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: workshop
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://workshop-vault.vault.azure.net/"
      serviceAccountRef:
        name: workshop-sa