kind: Namespace
apiVersion: v1
metadata:
  name: workshop
  labels:
    name: workshop

---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: workshop
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-sqr2klsnuxgxa.vault.azure.net/"
      serviceAccountRef:
        name: workshop-sa