kind: Namespace
apiVersion: v1
metadata:
  name: workshop
  labels:
    name: workshop

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: workshop
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
