kind: Namespace
apiVersion: v1
metadata:
  name: workshop
  labels:
    name: workshop

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: workshop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-store
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: pg-username
    remoteRef:
      key: PostgresUsername
  - secretKey: pg-password
    remoteRef:
      key: PostgresPassword