apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: workshop
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /svelte
        backend:
          service:
            name: frontend
            port:
              number: 80
        pathType: Prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: workshop
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: k8sworkshop404.azurecr.io/sample/frontend:0.1.0-node
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pg-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pg-username
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 500Mi
