kind: Namespace
apiVersion: v1
metadata:
  name: workshop
  labels:
    name: workshop
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: workshop
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: k8sworkshop404.azurecr.io/sample/frontend:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 500Mi
