apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ඞඞඞ
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: ඞඞඞ
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      # change this to your own path
      - path: /ඞඞඞ # <subdirectory>
        backend:
          service:
            name: frontend
            port:
              number: 80
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ඞඞඞ
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: workshopacrsqr2klsnuxgxa.azurecr.io/ඞඞඞ/<navn>:versjon
        imagePullPolicy: Always