kind: Namespace
apiVersion: v1
metadata:
  name: workshop
  labels:
    name: workshop
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: workshop
  labels:
    app: postgres
spec:
  ports:
  - port: 5454
    targetPort: 5454
  selector:
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: workshop
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: pass
  POSTGRES_DB: todo
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-storage
  namespace: workshop
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  namespace: workshop
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: azure-storage
      containers:
      - name: database
        image: k8sworkshop404.azurecr.io/sample/postgres:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: postgres-config
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 500Mi
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
