apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: ඞඞඞ
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-sqr2klsnuxgxa.vault.azure.net/"
      serviceAccountRef:
        name: key-vault-sa