apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: ඞඞඞ
  labels:
    app: ඞඞඞ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ඞඞඞ
  template:
    metadata:
      labels:
        app: ඞඞඞ
    spec:
      containers:
      - name: database
        image: workshopacrsqr2klsnuxgxa.azurecr.io/ඞඞඞ/name:0.1.0
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"