apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: ඞඞඞ
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-store
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: pg-username
    remoteRef:
      key: PostgresUsername-ඞඞඞ
  - secretKey: pg-password
    remoteRef:
      key: PostgresPassword-ඞඞඞ