apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  namespace: alex2
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "workshopacr3yfmswjfskxhc.azurecr.io/alex/aspnet:2"
    name: aspnetapp-image
    ports:
    - containerPort: 8080
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
  namespace: alex2
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetapp
  namespace: alex2
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      # change this to your own path
      - path: /hmm # <subdirectory>
        backend:
          service:
            name: aspnetapp
            port:
              number: 80
        pathType: Prefix